td_biblio/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = "td_biblio"
urlpatterns = [
    # Entry List
    url("^$", views.EntryListView.as_view(), name="entry_list"),
    url("^import/$", views.EntryBatchImportView.as_view(), name="import"),
    url("^duplicates/$", views.FindDuplicatedAuthorsView.as_view(), name="duplicates"),
]

td_biblio/templates/_layouts/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <!-- CSS Reset -->
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
    <!-- Milligram CSS minified -->
    <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
    <!-- Override styles -->
    <link rel="stylesheet" href="{% static "styles.css" %}">
    <title>TailorDev Biblio - {% block page_title %}{% endblock %}</title>
  </head>
  <body class="{% block page_class %}demo{% endblock page_class %}">
    {% block body %}
    <header id="page-header">
      <h1>
        <a href="{% url 'td_biblio:entry_list' %}">
          TailorDev Biblio
        </a>
        <span>
          // a Django app to manage your references.
        </span>
      </h1>
    </header>

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    <div role="main">
      {% block content %}{% endblock content %}
    </div>

    <footer id="page-footer">
      Brought to you by <a href="https://tailordev.fr">TailorDev</a> &mdash;
      Licensed under the MIT License.
    </footer>

    {% block javascripts %}{% endblock javascripts %}
    {% endblock %}
  </body>
</html>