td_biblio/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = "td_biblio"
urlpatterns = [
    # Entry List
    url("^$", views.EntryListView.as_view(), name="entry_list"),
    url("^import/$", views.EntryBatchImportView.as_view(), name="import"),
    url("^duplicates/$", views.FindDuplicatedAuthorsView.as_view(), name="duplicates"),
]

td_biblio/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import ugettext_lazy as _


class AbstractHuman(models.Model):
    """Simple Abstract Human model

    Note that this model may be linked to django registered users
    """

    first_name = models.CharField(_("First name"), max_length=100)
    last_name = models.CharField(_("Last name"), max_length=100)
    first_initial = models.CharField(_("First Initial(s)"), max_length=10, blank=True)

    # This is a django user
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE
    )

    alias = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        related_name="aliases",
        related_query_name="alias_human",
        blank=True,
        null=True,
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.get_formatted_name()

    def save(self, *args, **kwargs):
        """Set initials and try to set django user before saving"""

        self._set_first_initial()
        self._set_user()
        super(AbstractHuman, self).save(*args, **kwargs)

    def _set_first_initial(self, force=False):
        """Set author first name initial"""

        if self.first_initial and not force:
            return
        self.first_initial = " ".join([c[0] for c in self.first_name.split()])

    def get_formatted_name(self):
        """Return author formated full name, e.g. Maupetit J"""

        return "%s %s" % (self.last_name, self.first_initial)

    def _set_user(self):
        """Look for local django user based on human name"""

        if "" in (self.last_name, self.first_name):
            return

        self._set_first_initial()

        User = get_user_model()
        try:
            self.user = User.objects.get(
                models.Q(last_name__iexact=self.last_name),
                models.Q(first_name__iexact=self.first_name)
                | models.Q(first_name__istartswith=self.first_initial[0]),
            )
        except User.DoesNotExist:
            pass
        except User.MultipleObjectsReturned:
            pass


class Author(AbstractHuman):
    """Entry author"""

    class Meta:
        ordering = ("last_name", "first_name")
        verbose_name = _("Author")
        verbose_name_plural = _("Authors")


class Editor(AbstractHuman):
    """Journal or book editor"""

    class Meta:
        ordering = ("last_name", "first_name")
        verbose_name = _("Editor")
        verbose_name_plural = _("Editors")


class AbstractEntity(models.Model):
    """Simple abstract entity"""

    name = models.CharField(_("Name"), max_length=150)
    abbreviation = models.CharField(
        _("Entity abbreviation"),
        max_length=100,
        blank=True,
        help_text=_("e.g. Proc Natl Acad Sci U S A"),
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Journal(AbstractEntity):
    """Peer reviewed journal"""

    class Meta:
        verbose_name = _("Journal")
        verbose_name_plural = _("Journals")


class Publisher(AbstractEntity):
    """Journal or book publisher"""

    class Meta:
        verbose_name = _("Publisher")
        verbose_name_plural = _("Publishers")


class Entry(models.Model):
    """The core model for references

    Largely guided by the BibTeX file format (see
    http://en.wikipedia.org/wiki/BibTeX).

    Unsupported fields (for now):

    * eprint: A specification of an electronic publication, often a preprint
      or a technical report
    * howpublished: How it was published, if the publishing method is
      nonstandard
    * institution: The institution that was involved in the publishing, but not
      necessarily the publisher
    * key: A hidden field used for specifying or overriding the alphabetical
      order of entries (when the "author" and "editor" fields are missing).
      Note that this is very different from the key (mentioned just after this
      list) that is used to cite or cross-reference the entry.
    * series: The series of books the book was published in (e.g. "The Hardy
      Boys" or "Lecture Notes in Computer Science")
    * type: The field overriding the default type of publication (e.g.
      "Research Note" for techreport, "{PhD} dissertation" for phdthesis,
      "Section" for inbook/incollection)
    """

    ARTICLE = "article"
    BOOK = "book"
    BOOKLET = "booklet"
    CONFERENCE = "conference"
    INBOOK = "inbook"
    INCOLLECTION = "incollection"
    INPROCEEDINGS = "inproceedings"
    MANUAL = "manual"
    MASTERSTHESIS = "mastersthesis"
    MISC = "misc"
    PHDTHESIS = "phdthesis"
    PROCEEDINGS = "proceedings"
    TECHREPORT = "techreport"
    UNPUBLISHED = "unpublished"

    ENTRY_TYPES_CHOICES = (
        (ARTICLE, _("Article")),
        (BOOK, _("Book")),
        (BOOKLET, _("Book (no publisher)")),
        (CONFERENCE, _("Conference")),
        (INBOOK, _("Book chapter")),
        (INCOLLECTION, _("Book from a collection")),
        (INPROCEEDINGS, _("Conference proceedings article")),
        (MANUAL, _("Technical documentation")),
        (MASTERSTHESIS, _("Master's Thesis")),
        (MISC, _("Miscellaneous")),
        (PHDTHESIS, _("PhD Thesis")),
        (PROCEEDINGS, _("Conference proceedings")),
        (TECHREPORT, _("Technical report")),
        (UNPUBLISHED, _("Unpublished work")),
    )

    type = models.CharField(
        _("Entry type"), max_length=50, choices=ENTRY_TYPES_CHOICES, default=ARTICLE
    )

    # Base fields
    title = models.CharField(_("Title"), max_length=255)
    authors = models.ManyToManyField(
        "Author", related_name="entries", through="AuthorEntryRank"
    )
    journal = models.ForeignKey(
        "Journal", related_name="entries", blank=True, on_delete=models.CASCADE
    )
    publication_date = models.DateField(_("Publication date"), null=True)
    is_partial_publication_date = models.BooleanField(
        _("Partial publication date?"),
        default=True,
        help_text=_(
            "Check this if the publication date is incomplete (for example "
            "if only the year is valid)"
        ),
    )
    volume = models.CharField(
        _("Volume"),
        max_length=50,
        blank=True,
        help_text=_("The volume of a journal or multi-volume book"),
    )
    number = models.CharField(
        _("Number"),
        max_length=50,
        blank=True,
        help_text=_(
            "The '(issue) number' of a journal, magazine, or tech-report, if "
            "applicable. (Most publications have a 'volume', but no 'number' "
            "field.)"
        ),
    )
    pages = models.CharField(
        _("Pages"),
        max_length=50,
        blank=True,
        help_text=_("Page numbers, separated either by commas or " "double-hyphens"),
    )
    url = models.URLField(
        _("URL"), blank=True, help_text=_("The WWW address where to find this resource")
    )

    # Identifiers
    doi = models.CharField(
        _("DOI"),
        max_length=100,
        blank=True,
        help_text=_("Digital Object Identifier for this resource"),
    )
    issn = models.CharField(
        _("ISSN"),
        max_length=20,
        blank=True,
        help_text=_("International Standard Serial Number"),
    )
    isbn = models.CharField(
        _("ISBN"),
        max_length=20,
        blank=True,
        help_text=_("International Standard Book Number"),
    )
    pmid = models.CharField(
        _("PMID"), blank=True, max_length=20, help_text=_("Pubmed ID")
    )

    # Book
    booktitle = models.CharField(
        _("Book title"),
        max_length=50,
        blank=True,
        help_text=_("The title of the book, if only part of it is being cited"),
    )
    edition = models.CharField(
        _("Edition"),
        max_length=100,
        blank=True,
        help_text=_(
            "The edition of a book, long form (such as 'First' or " "'Second')"
        ),
    )
    chapter = models.CharField(_("Chapter number"), max_length=50, blank=True)

    # PhD Thesis
    school = models.CharField(
        _("School"),
        max_length=50,
        blank=True,
        help_text=_("The school where the thesis was written"),
    )

    # Proceedings
    organization = models.CharField(
        _("Organization"),
        max_length=50,
        blank=True,
        help_text=_("The conference sponsor"),
    )

    # Misc
    editors = models.ManyToManyField("Editor", related_name="entries", blank=True)
    publisher = models.ForeignKey(
        "Publisher",
        related_name="entries",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    address = models.CharField(
        _("Address"),
        max_length=250,
        blank=True,
        help_text=_(
            "Publisher's address (usually just the city, but can be the full "
            "address for lesser-known publishers)"
        ),
    )
    annote = models.CharField(
        _("Annote"),
        max_length=250,
        blank=True,
        help_text=_("An annotation for annotated bibliography styles (not typical)"),
    )
    note = models.TextField(
        _("Note"), blank=True, help_text=_("Miscellaneous extra information")
    )

    # Related publications
    crossref = models.ManyToManyField("self", blank=True)

    class Meta:
        verbose_name = _("Entry")
        verbose_name_plural = _("Entries")
        ordering = ("-publication_date",)

    def __str__(self):
        """Format entry with a default bibliography style"""
        # Authors
        author_str = "%(last_name)s %(first_initial)s"
        s = ", ".join([author_str % a.__dict__ for a in self.get_authors()])
        s = ", and ".join(s.rsplit(", ", 1))  # last author case
        s += ", "

        # Title
        s += '"%(title)s", ' % self.__dict__

        # Journal

td_biblio/templates/td_biblio/entry_import.html
{% extends "td_biblio/layouts/one_col.html" %}
{% load i18n %}

{% block page_title %}{% trans "Import publications" %}{% endblock page_title %}

{% block page_class %}page biblio import{% endblock page_class %}

{% block main_content %}

<h2>{% trans "Import new publications" %}</h2>

<form
  class="batch-import-form"
  action="{% url 'td_biblio:import' %}"
  method="post"
>
  {% csrf_token %}

  {{ form }}

  <div class="form-actions">
    <input
      type="reset"
      name="{% trans "Cancel" %}"
      value="{% trans "cancel" %}"
      class="cancel"
    >
    <input
      type="submit"
      name="{% trans "Import" %}"
      value="{% trans "submit" %}"
      class="submit"
    >
  </div>
</form>

{% endblock main_content %}

td_biblio/templates/td_biblio/entry_item.html
{% include "td_biblio/bibliography_styles/ieeetr.html" %}

td_biblio/templates/td_biblio/entry_list.html
{% extends "td_biblio/layouts/two_cols_left_sidebar.html" %}
{% load i18n %}

{% block page_title %}{% trans "Publications" %}{% endblock page_title %}

{% block page_class %}page biblio{% endblock page_class %}

{% block left_sidebar_extras %}

<h3>{% trans "Metrics" %}</h3>

<div id="publications-stats">
    <table>
        <tr class="metric">
            <td>{% trans "Publications" %}</td>
            <td><span class="counter">{{ n_publications_filter }}</span></td>
            <td>{{ n_publications_total }}</td>
        </tr>
        <tr class="metric">
            <td>{% trans "Authors" %}</td>
            <td><span class="counter">{{ n_authors_filter }}</span></td>
            <td>{{ n_authors_total }}</td>
        </tr>
        <tr class="metric">
            <td>{% trans "Journals" %}</td>
            <td><span class="counter">{{ n_journals_filter }}</span></td>
            <td>{{ n_journals_total }}</td>
        </tr>
    </table>

    <div class="legend">
        <span class="counter">XX</span> {% trans "after filtering" %}
    </div>
</div>

<h3>{% trans "Filters" %}</h3>

<form method="get" action="" id="publication-list-filters" class="custom">

    <label for="filter-year">{% trans "Year" %}</label>
    <select name="year" id="filter-year">
        <option value="">
            {% trans "All" %}
        </option>
        {% for publication_year in publication_years %}
        <option value="{{ publication_year.year }}" {% if publication_year.year == current_publication_year.year %}selected="selected"{% endif %}>
            {{ publication_year.year }}
        </option>
        {% endfor %}
    </select>

    <label for="filter-author">{% trans "Author" %}</label>
    <select name="author" id="filter-author">
        <option value="">
            {% trans "All" %}
        </option>
        {% for author in publication_authors %}
        <option value="{{ author.id }}" {% if author.id == current_publication_author %}selected="selected"{% endif %}>
            {{ author.get_formatted_name }}
        </option>
        {% endfor %}
    </select>

    <label for="filter-collection">{% trans "Collection" %}</label>
    <select name="collection" id="filter-collection">
        <option value="">
            {% trans "All" %}
        </option>
        {% for collection in publication_collections %}
        <option value="{{ collection.id }}" {% if collection.id == current_publication_collection %}selected="selected"{% endif %}>
            {{ collection.name }}
        </option>
        {% endfor %}
    </select>
</form>
{% endblock left_sidebar_extras %}

{% block main_content %}

<h2>{% trans "Publications" %}</h2>

{% if request.user.is_superuser %}
<div class="import-message">
  Hi <strong>{{ request.user.username }}</strong>!
  {% blocktrans %}
  As an adminstrator of this application you can import new references with
  DOIs or PubMed ids.
  {% endblocktrans %}
  <a href="{% url 'td_biblio:import' %}" class="button import">
    Add references
  </a>
</div>
{% endif %}

{% include "td_biblio/partials/publication_list_by_year.html" with publications=entry_list %}

{% if is_paginated %}
<div class="pagination-centered">

    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}" class="pagination">&laquo;</a></li>
        {% endif %}
        <li class="current">
            <a href="">{{ page_obj.number }}</a>
            {{ page_obj.start_index }} - {{ page_obj.end_index }}</li>
        {% if page_obj.has_next %}
        <li class="arrow"><a href="?page={{ page_obj.next_page_number }}" class="pagination">&raquo;</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}

{% endblock main_content %}

td_biblio/templates/td_biblio/find_duplicated_authors.html
{% extends "td_biblio/layouts/one_col.html" %}
{% load i18n %}

{% block page_title %}{% trans "Find duplicated authors" %}{% endblock page_title %}

{% block page_class %}page biblio duplicated{% endblock page_class %}

{% block main_content %}

<h2>{% trans "Author duplicates manager" %}</h2>

{% if form.errors %}
<div class="form-errors">
    <h5>{% trans "Unexpected errors" %}</h5>

    {{ form.errors }}
</div>
{% endif %}

<form name="duplicates" class="duplicates-form" action="" method="post">
  {% csrf_token %}
  <table>
    <thead>
      <tr>
        <th>{% trans "Last name" %}</th>
        <th>{% trans "First name" %}</th>
        <th>{% trans "First Initial(s)" %}</th>
        <th>{% trans "# Aliases" %}</th>
        <th>{% trans "Selection" %}</th>
        <th>{% trans "Alias" %}</th>
      </tr>
    </thead>
    <tbody>
        {% for author in author_list  %}
        <tr>
          <td>{{ author.last_name }}</td>
          <td>{{ author.first_name }}</td>
          <td>{{ author.first_initial }}</td>
          <td>{{ author.aliases.count | default:"-" }}</td>
          <td>
            <input type="checkbox" name="authors" value="{{ author.id }}">
          </td>
          <td>
            <input type="radio" name="alias" value="{{ author.id }}">
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="form-actions">
    <button type="reset" name="button" class="button button-outline">
      {% trans "Reset" %}
    </button>
    <button type="submit" name="button" class="button">
      {% trans "Submit" %}
    </button>
  </div>
</form>

{% if is_paginated %}
<div class="pagination-wrapper">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}&amp;by={{ paginate_by }}" class="pagination">&laquo;</a></li>
        {% endif %}
        <li class="current">
            <a href="">{{ page_obj.number }}</a>
            {{ page_obj.start_index }} - {{ page_obj.end_index }}</li>
        {% if page_obj.has_next %}
        <li class="arrow"><a href="?page={{ page_obj.next_page_number }}&amp;by={{ paginate_by }}" class="pagination">&raquo;</a></li>
        {% endif %}
    </ul>

    <form class="paginate-by-form" action="" method="get">
      <input type="hidden" name="page" value="{{ page_obj.number }}">
      <fieldset>
        <label for="paginate-by">{% trans "Paginate by:" %}</label>
        <select id="paginate-by" name="by">
          <option value="30" {% if paginate_by == 30 %}selected="selected"{% endif %}>30</option>
          <option value="50" {% if paginate_by == 50 %}selected="selected"{% endif %}>50</option>
          <option value="100" {% if paginate_by == 100 %}selected="selected"{% endif %}>100</option>
          <option value="200" {% if paginate_by == 200 %}selected="selected"{% endif %}>200</option>
          <option value="500" {% if paginate_by == 500 %}selected="selected"{% endif %}>500</option>
          <option value="1000" {% if paginate_by == 1000 %}selected="selected"{% endif %}>1000</option>
        </select>
        <button type="submit" class="button">{% trans "Reload" %}</button>
      </fieldset>
    </form>
</div>
{% endif %}

{% endblock main_content %}